[package]
name = "prac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.14.13"
borsh = "0.10.0"
borsh-derive = "0.10.0"

[lib]
crate-type = ["cdylib", "lib"]